### ISSUE TITLE
Export isn't working

### ISSUE THREAD

**Issue by o01eg** [bend-n/godot-actions#8]
### What happened?

When I'm trying to export android build I get errors.

If I don't use separate setup step:
```
Setup godot
  fatal: detected dubious ownership in repository at '/__w/freeorion/freeorion'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/freeorion/freeorion
  fatal: detected dubious ownership in repository at '/__w/freeorion/freeorion'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /__w/freeorion/freeorion
  python: can't open file '/__w/freeorion/freeorion/godot/pv.py': [Errno 2] No such file or directory
  Error: Process completed with exit code 2.
```

If I use separate setup step:

```
Setup godot
  mv: cannot stat '/root/.config/godot/editor_settings-3.tres': No such file or directory
  Error: Process completed with exit code 1.
```

### Workflow

```YAML
name: "Android build"

on:
  push:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
  pull_request:
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'

jobs:
  generate-godot-api:
    name: Generate Godot API
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bend-n/godot:3.5
    steps:
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5
      - name: Generate API file
        run: |
          timeout 1m godot --no-window --disable-render-loop --video-driver Dummy --gdnative-generate-json-api godot-api.json
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: godot-api
          path: godot-api.json
          if-no-files-found: error
          retention-days: 1
  build-android:
    name: Android ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: generate-godot-api
    strategy:
      matrix:
        arch: [x86, x86_64, armeabi-v7a, arm64-v8a]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Dowload Godot API
        uses: actions/download-artifact@v3
        with:
          name: godot-api
          path: .
      - name: Download SDK
        id: download-sdk
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v13/FreeOrionSDK_13_Android-${{ matrix.arch }}.zip
          target: ../
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24
          add-to-path: false
      - name: Configure
        run: |
          unzip -q ../${{ steps.download-sdk.outputs.filename }} -d ..
          GODOT_API_JSON=$(realpath godot-api.json)
          mkdir build
          pushd build
          FO_SDK=$(realpath ../..)
          cmake -DANDROID_ABI=${{ matrix.arch }} -DANDROID_PLATFORM=24 -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DCMAKE_CXX_FLAGS=-std=c++14 -DANDROID_ALLOW_UNDEFINED_SYMBOLS=Off -DBUILD_SERVER=OFF -DBUILD_AI=OFF -DBUILD_CLIENT_GG=OFF -DBoost_INCLUDE_DIR=${FO_SDK}/include/ -DBoost_USE_STATIC_LIBS=On -DBoost_LIBRARY_DIR=${FO_SDK}/lib/ -DBUILD_CLIENT_GODOT=On -DICUI18N_LIBRARY=${FO_SDK}/lib/libicui18n.a -DICUUC_LIBRARY=${FO_SDK}/lib/libicuuc.a -DICUDATA_LIBRARY=${FO_SDK}/lib/libicudata.a -DICONV_LIBRARY=${FO_SDK}/lib/libiconv.so -DPYTHON_LIBRARY=${FO_SDK}/lib/libpython3.9.a -DPYTHON_INCLUDE_DIR=${FO_SDK}/include/python3.9/ -DGODOT_CUSTOM_API_FILE=${GODOT_API_JSON} ..
      - name: Build
        run: |
          pushd build
          cmake --build . -- -j2
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: android-binaries
          path: godot/bin/
          if-no-files-found: error
          retention-days: 1
  export-android:
    name: Export Android
    runs-on: ubuntu-latest
    needs: build-android
    container:
      image: ghcr.io/bend-n/godot:3.5
    steps:
      - name: Setup
        uses: bend-n/godot-actions/.github/actions/setup-godot@main
        env:
          GODOT_VERSION: 3.5
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Download python library
        id: download-python-lib
        uses: suisei-cn/actions-download-file@v1.3.0
        with:
          url: https://github.com/freeorion/freeorion-sdk/releases/download/v13/python39.zip
          target: ../
      - name: Place resources
        run: |
          mkdir -p godot/default/python/lib/
          cp ../${{ steps.download-python-lib.outputs.filename }} godot/default/python/lib/python39.zip
          unzip -t godot/default/python/lib/python39.zip
          mv default/data/art godot/assets/
          mv default/data/fonts godot/assets/
          mv default/data/sound godot/assets/
          mv default/scripting godot/default/
          mv default/stringtables godot/default/
      - name: Dowload binaries
        uses: actions/download-artifact@v3
        with:
          name: android-binaries
          path: godot/bin/
      - name: Build
        uses: bend-n/godot-actions/.github/actions/export-android@main
        env:
          GODOT_VERSION: 3.5
          NAME: freeorion
          PROJECT_PATH: godot
```

### Logs

With setup https://github.com/o01eg/freeorion/actions/runs/3636462372/jobs/6136623350

Without setup https://github.com/o01eg/freeorion/actions/runs/3636114345/jobs/6135944505

### Version

main

**Comment by bend-n** [comment]
It would seem that not testing that last commit was a bad idea.

Its trying to set up twice here... https://github.com/o01eg/freeorion/actions/runs/3636462372/jobs/6136623350

**Comment by bend-n** [comment]
Oh, oops. I had `if hasnt_run: has_run = true else run` logic pretty much.

**Comment by bend-n** [comment]
It should be fixed, please try it.

**Comment by o01eg** [comment]
Still same errors in both cases:

https://github.com/o01eg/freeorion/actions/runs/3636462372/jobs/6137364617

https://github.com/o01eg/freeorion/actions/runs/3636966448/jobs/6137663846

**Comment by bend-n** [comment]
Oh?

I don't understand the error on the second one actually.

Wait, i figured out the second error. But i still want the first one to work ._.

**Comment by bend-n** [comment]
@o01eg method 2 *will* work now, but im not sure about method one.

**Comment by o01eg** [comment]
Still fails https://github.com/o01eg/freeorion/actions/runs/3636966448/jobs/6138392834

**Comment by bend-n** [comment]
okay what, curl isnt a command? that is *not* what i was expecting. changed to wget.

**Comment by bend-n** [comment]
If setupping multiple times doesnt work though, the android-build action will fail, as it does that.

**Comment by bend-n** [comment]
I could make a workaround, but i would prefer for my system to work.

**Comment by o01eg** [comment]
Wged uses different options https://github.com/o01eg/freeorion/actions/runs/3636966448/jobs/6138745252

**Comment by bend-n** [comment]
So, funny story.

\> Tested functionality with wget
\> Changed to curl for some reason, added -s flag
\> Didnt test if curl was on container
\> Didnt test if curl flags worked
\> Changed back to wget
\> Forget to remove -s flag
\> Remove -s flag
\> Forget to re-add -q flag
\> Add -q flag

**Comment by o01eg** [comment]
Better but now. Not sure what is wrong now: https://github.com/o01eg/freeorion/actions/runs/3636966448/jobs/6139519706

**Comment by bend-n** [comment]
I tried to fork and run it, why does it take so long? https://github.com/o01eg/freeorion/actions/runs/3636966448/jobs/6139519706#step:7:4174 this seem to be the problem. Path issues.

**Comment by bend-n** [comment]
https://github.com/bend-n/citest/actions/runs/3637905453/jobs/6139696547#step:7:4132 im happy this worked.

**Comment by bend-n** [comment]
Path issues are unrelated.

**Comment by o01eg** [comment]
Path issues in second variant without separate setup step related to that part happened in export step.

```
2022-12-07T10:18:44.2793906Z ##[group]Cleaning the repository
2022-12-07T10:18:44.2794080Z [command]/usr/bin/git clean -ffdx
2022-12-07T10:18:44.3264629Z Removing godot/assets/art/
2022-12-07T10:18:44.3264898Z Removing godot/assets/fonts/
2022-12-07T10:18:44.3265509Z Removing godot/assets/sound/
2022-12-07T10:18:44.3265717Z Removing godot/bin/
2022-12-07T10:18:44.3265911Z Removing godot/default/
2022-12-07T10:18:44.3286773Z [command]/usr/bin/git reset --hard HEAD
2022-12-07T10:18:45.0498034Z HEAD is now at cd4cdb1 Export Android APK in CI
2022-12-07T10:18:45.0603934Z ##[endgroup]
```

Looks like separate step is required for non-clean repo.

**Comment by bend-n** [comment]
What do you mean?

**Comment by o01eg** [comment]
I mean setup calls to clean repository after I download files and place links in repository so I should first setup Godot and then make changes.

**Comment by bend-n** [comment]
That seems strange. Must be some kin of behaviour when actions/checkout-ing multiple times.

**Comment by bend-n** [comment]
@o01eg it should be fixed now. I checkout the repo to a separate directory so there should be no conflicts.

**Comment by bend-n** [comment]
Oops, i accidentally `git reset HEAD^` and then `amend -pa`-ed.
